version: '3'
services:
  nginx:
    build:
      context: ../
      cache_from:
        - alpine:edge
        - vsokolyk/mozjpeg
    container_name: nginx-buster
    depends_on:
      - redis
    ports:
      - 80:80
      - 443:443
    tty: true
    tmpfs: /var/cache
    restart: unless-stopped
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./../conf/html/nginx:/conf/html/nginx
      - ./../conf/html/monit:/conf/html/monit
      - ./../approot:/usr/share/nginx/html
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
#    env_file:
#      - ./../env/html.env
  redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: redis
