version: '3'
services:
  nginx:
    build:
      context: ../
      cache_from:
        - alpine:edge
        - vsokolyk/mozjpeg
    container_name: nginx-buster
    environment:
      NGINX_SERVER_NAME: my-local-site
#    depends_on:
#      - redis
    ports:
      - 80:80
      - 443:443
    tty: true
    tmpfs: /var/cache
    restart: unless-stopped
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./../conf/html:/etc/nginx
      - ./../approot:/usr/share/nginx/html
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
#  redis:
#    image: redis:alpine
#    restart: unless-stopped
#    container_name: redis
