version: '3'
services:
  nginx:
    build:
      context: ../
      cache_from:
        - alpine:edge
        - vsokolyk/mozjpeg
    container_name: nginx-buster
    environment:
      - NGINX_SERVER_NAME=nginx-buster
      - PHP_FPM_UPSTREAM=false
      - REDIS_UPSTREAM=false
      - NOCACHE_COOKIE=comment_author wp-postpass wordpress_test_cookie wordpress_no_cache wordpress_logged_in
#    depends_on:
#      - redis
    ports:
      - 80:80
      - 443:443
    tty: true
    tmpfs: /var/cache
    restart: unless-stopped
    volumes:
#      - ./ssl-certs:/etc/certs:rw
      - ./template:/nginx-template
#      - ./../conf/html:/etc/nginx
      - ./../approot:/usr/share/nginx/html
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
#  redis:
#    image: redis:alpine
#    restart: unless-stopped
#    container_name: redis
